name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  velocity_x: ^4.1.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.13
  shared_preferences: ^2.2.2
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf
    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf
    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
