import 'package:get/get.dart';
import 'package:shopwithme/constants/images.dart';
import 'package:shopwithme/models/product_model.dart';

class ProductController extends GetxController {
  var quantity = 1.obs;
  var colorIndex = 0.obs;
  var currentProductTitle = ''.obs;
  var currentProductPrice = 0.0.obs;
  var favorites = <int>[].obs;
  var currentProduct = Rx<Product?>(null);
  var currentCategory = ''.obs;
  final RxList<Product> relatedProducts = <Product>[].obs;
  var sizeIndex = 0.obs;
  final RxList<Product> cartItems = <Product>[].obs;
  final RxDouble cartTotal = 0.0.obs;

  final Map<String, List<Product>> categoryProducts = {
    'Women Clothing': [
      Product(
        title: "Summer Floral Dress",
        price: 49.99,
        image: "https://i.pinimg.com/564x/c9/94/3b/c9943b7bc3611c684d4bee67e2481259.jpg",
        category: "Women Clothing",
        colors: ["Red", "Blue", "Green"],
        sizes: ["XS", "S", "M", "L", "XL"],
        description: """
          Beautiful floral summer dress perfect for any occasion. Made with high-quality breathable fabric.
          
          • Lightweight and comfortable
          • 100% cotton material
          • Adjustable waist tie
          • Side pockets
          • Machine washable
          """,
        rating: 4.8,
        reviews: 128,
        brand: "Summer Bloom",
        material: "100% Cotton",
        careInstructions: [
          "Machine wash cold",
          "Tumble dry low",
          "Do not bleach",
          "Iron on low heat"
        ],
        features: [
          "Breathable fabric",
          "Side pockets",
          "Adjustable waist",
          "Lined bodice"
        ],
        inStock: true,
        deliveryTime: "2-4 business days",
        id: "1",
      ),
      Product(
        title: "Evening Gown",
        price: 129.99,
        image: "https://i.pinimg.com/564x/89/c9/1f/89c91f991e599c81195b04e487e4f4f4.jpg",
        category: "Women Clothing",
        colors: ["Black", "Navy", "Burgundy"],
        description: "Elegant evening gown with delicate embroidery and flowing silhouette",
        brand: "Elegance",
        material: "Silk Blend",
        features: ["Embroidered details", "Full lining", "Hidden zipper", "Sweep train"],
        careInstructions: ["Dry clean only", "Store in garment bag", "Steam to remove wrinkles"],
        id: "2",
      ),
      Product(
        title: "Casual Maxi Dress",
        price: 59.99,
        image: "https://i.pinimg.com/564x/42/44/09/4244097d369d9fe2a38b1a9a8a60b786.jpg",
        category: "Women Clothing",
        colors: ["Yellow", "Pink", "White"],
        description: "Flowy maxi dress perfect for summer days",
        brand: "Sunshine Wear",
        material: "Rayon",
        features: ["Adjustable straps", "Side slits", "Elastic waist"],
        careInstructions: ["Machine wash cold", "Line dry", "Do not bleach"],
        id: "3",
      ),
      Product(
        title: "Cocktail Dress",
        price: 89.99,
        image: "https://i.pinimg.com/564x/d5/0a/c8/d50ac8558111b5187e92f249571e01c4.jpg",
        category: "Women Clothing",
        colors: ["Red", "Black", "Silver"],
        description: "Stylish cocktail dress for special events",
        brand: "GlamourStyle",
        material: "Polyester Blend with Sequins",
        features: ["Fitted silhouette", "Hidden zipper", "Lined interior", "Stretch fabric"],
        careInstructions: ["Dry clean only", "Store hanging", "Avoid direct sunlight"],
        id: "4",
      ),
      Product(
        title: "Wrap Dress",
        price: 69.99,
        image: "https://i.pinimg.com/564x/15/7d/c0/157dc0947d02d54c92b3f0f7916b66c4.jpg",
        category: "Women Clothing",
        colors: ["Green", "Blue", "Purple"],
        description: "Versatile wrap dress suitable for work and leisure",
        brand: "DailyChic",
        material: "Jersey Knit",
        features: ["True wrap style", "Belt included", "Knee length", "V-neckline"],
        careInstructions: ["Machine wash cold", "Hang dry", "Do not bleach"],
        id: "5",
      ),
      Product(
        title: "Bohemian Maxi Dress",
        price: 79.99,
        image: "https://i.pinimg.com/564x/a8/f5/4f/a8f54f727a5d6391b8618a9dc2b38891.jpg",
        category: "Women Clothing",
        colors: ["Orange", "Yellow", "Red"],
        description: "Flowy bohemian style maxi dress perfect for summer",
        brand: "BohoChic",
        material: "Rayon Blend",
        features: ["Empire waist", "Flutter sleeves", "Tiered skirt", "Floral print"],
        careInstructions: ["Hand wash cold", "Line dry", "Do not bleach"],
        id: "6",
      ),
      Product(
        title: "Business Pencil Dress",
        price: 89.99,
        image: imgP1,
        category: "Women Clothing",
        colors: ["Black", "Navy", "Grey"],
        description: "Professional pencil dress for office wear",
        brand: "WorkStyle",
        material: "Polyester Blend with Spandex",
        features: ["Back vent", "Lined", "Knee length", "Hidden zipper"],
        careInstructions: ["Dry clean", "Steam to remove wrinkles", "Store on hanger"],
        id: "7",
      ),
      Product(
        title: "Party Sequin Dress",
        price: 119.99,
        image: imgP1,
        category: "Women Clothing",
        colors: ["Gold", "Silver", "Rose Gold"],
        description: "Glamorous sequin dress for special occasions",
        brand: "GlamNight",
        material: "Sequin Mesh",
        features: ["Full lining", "Side slit", "Padded bust", "Stretch fit"],
        careInstructions: ["Dry clean only", "Store flat", "Avoid direct sunlight"],
        id: "8",
      ),
      Product(
        title: "Casual T-shirt Dress",
        price: 39.99,
        image: imgP1,
        category: "Women Clothing",
        colors: ["Grey", "Black", "Navy"],
        description: "Comfortable t-shirt dress for everyday wear",
        brand: "ComfortDaily",
        material: "Cotton Jersey",
        features: ["Relaxed fit", "Side pockets", "Above knee length", "Crew neck"],
        careInstructions: ["Machine wash cold", "Tumble dry low", "Do not iron print"],
        id: "9",
      ),
      Product(
        title: "Summer Mini Dress",
        price: 49.99,
        image: imgP1,
        category: "Women Clothing",
        colors: ["Pink", "Blue", "White"],
        description: "Light and breezy mini dress for hot days",
        brand: "SummerVibes",
        material: "Cotton Blend",
        features: ["A-line cut", "Adjustable straps", "Built-in shorts", "Breathable fabric"],
        careInstructions: ["Machine wash cold", "Line dry", "Iron on low"],
        id: "10",
      ),
    ],
    'Men Clothing': [
      Product(
        title: "Casual Denim Jacket",
        price: 79.99,
        image: "https://i.pinimg.com/564x/8d/c5/0e/8dc50e533b8c8117b7f8f6d8f5349f7b.jpg",
        category: "Men Clothing",
        colors: ["Blue", "Black", "Grey"],
        description: "Classic denim jacket with modern fit and premium construction",
        brand: "DenimCo",
        material: "100% Cotton Denim",
        features: ["Adjustable cuffs", "Multiple pockets", "Button closure", "Reinforced stitching"],
        careInstructions: ["Machine wash cold", "Tumble dry low", "Do not bleach"],
        id: "11",
      ),
      Product(
        title: "Classic White Shirt",
        price: 45.99,
        image: "https://i.pinimg.com/564x/dd/b7/1b/ddb71b88c2428170c7236f5f9f615cbe.jpg",
        category: "Men Clothing",
        colors: ["White", "Light Blue", "Pink"],
        description: "Premium cotton dress shirt with wrinkle-resistant finish",
        brand: "Executive Wear",
        material: "Egyptian Cotton",
        features: ["Non-iron fabric", "Spread collar", "Adjustable cuffs", "Chest pocket"],
        careInstructions: ["Machine washable", "Warm iron if needed", "Do not bleach"],
        id: "12",
      ),
      Product(
        title: "Slim Fit Chinos",
        price: 59.99,
        image: "https://i.pinimg.com/564x/91/f8/1b/91f81b11f5e9c3962b3c9d524f8f60c4.jpg",
        category: "Men Clothing",
        colors: ["Khaki", "Navy", "Olive"],
        description: "Modern slim fit chinos with stretch comfort",
        brand: "Urban Threads",
        material: "98% Cotton, 2% Elastane",
        features: ["Stretch fabric", "Hidden phone pocket", "Wrinkle-resistant", "Flat front"],
        careInstructions: ["Machine wash cold", "Tumble dry low", "Iron if needed"],
        id: "13",
      ),
      Product(
        title: "Wool Blend Sweater",
        price: 89.99,
        image: "https://i.pinimg.com/564x/d7/a3/ae/d7a3ae5c686f6e7c88889c4c6b1d2c88.jpg",
        category: "Men Clothing",
        colors: ["Navy", "Charcoal", "Burgundy"],
        description: "Luxurious wool blend sweater for cold weather comfort",
        brand: "Cozy Knits",
        material: "80% Wool, 20% Polyester",
        features: ["Ribbed cuffs", "Crew neck", "Seamless construction", "Temperature regulating"],
        careInstructions: ["Hand wash cold", "Lay flat to dry", "Do not bleach", "Dry clean optional"],
        id: "14",
      ),
      Product(
        title: "Leather Belt",
        price: 34.99,
        image: imgP2,
        category: "Men Clothing",
        colors: ["Brown", "Black", "Tan"],
        description: "Genuine leather belt with classic buckle",
        brand: "LeatherCraft",
        material: "Full-grain Leather",
        features: ["Solid brass buckle", "Hand-stitched", "Reinforced holes", "Classic design"],
        careInstructions: ["Clean with leather cleaner", "Condition regularly", "Store rolled up"],
        id: "15",
      ),
      Product(
        title: "Casual Polo Shirt",
        price: 39.99,
        image: imgP2,
        category: "Men Clothing",
        colors: ["Navy", "White", "Grey"],
        description: "Classic polo shirt with moisture-wicking fabric",
        brand: "SportStyle",
        material: "Pima Cotton Blend",
        features: ["Breathable fabric", "UV protection", "No-curl collar", "Side vents"],
        careInstructions: ["Machine wash cold", "Tumble dry low", "Do not iron logo"],
        id: "16",
      ),
      Product(
        title: "Formal Suit",
        price: 299.99,
        image: imgP2,
        category: "Men Clothing",
        colors: ["Black", "Navy", "Charcoal"],
        description: "Premium wool blend suit with modern cut",
        brand: "TailorPro",
        material: "Italian Wool Blend",
        features: ["Half canvas construction", "Pick-stitched lapels", "Surgeon cuffs", "Interior pockets"],
        careInstructions: ["Dry clean only", "Use suit bag", "Steam to remove wrinkles"],
        id: "17",
      ),
      Product(
        title: "Sports Shorts",
        price: 29.99,
        image: imgP2,
        category: "Men Clothing",
        colors: ["Black", "Grey", "Navy"],
        description: "Comfortable athletic shorts with moisture-wicking technology",
        brand: "ActiveWear",
        material: "88% Polyester, 12% Spandex",
        features: ["Quick-dry fabric", "Side pockets", "Elastic waistband", "Reflective details"],
        careInstructions: ["Machine wash cold", "Tumble dry low", "No fabric softener"],
        id: "18",
      ),
      Product(
        title: "Winter Jacket",
        price: 129.99,
        image: imgP2,
        category: "Men Clothing",
        colors: ["Black", "Navy", "Olive"],
        description: "Insulated winter jacket with water-resistant finish",
        brand: "WinterTech",
        material: "Nylon with Down filling",
        features: ["800-fill down", "Storm cuffs", "Detachable hood", "Inner pocket"],
        careInstructions: ["Machine wash cold", "Tumble dry low", "Close zippers before washing"],
        id: "19",
      ),
      Product(
        title: "Dress Shoes",
        price: 89.99,
        image: imgP2,
        category: "Men Clothing",
        colors: ["Black", "Brown", "Tan"],
        description: "Classic leather dress shoes with premium construction",
        brand: "FootLuxe",
        material: "Genuine Leather",
        features: ["Leather sole", "Cushioned insole", "Blake stitching", "Breathable lining"],
        careInstructions: ["Polish regularly", "Use shoe trees", "Rotate wear"],
        id: "20",
      ),
    ],
    'Electronics': [
      Product(
        title: "Wireless Mouse",
        price: 29.99,
        image: "https://i.pinimg.com/564x/2c/e3/c7/2ce3c7c6c52f9c5283fadae0e309ae3e.jpg",
        category: "Electronics",
        colors: ["Black", "White", "Grey"],
        description: "High-precision wireless mouse with ergonomic design",
        brand: "TechPro",
        material: "ABS Plastic",
        features: ["1600 DPI", "Ergonomic design", "6-month battery life", "Silent clicks"],
        careInstructions: ["Clean with dry cloth", "Remove battery when not in use", "Store in cool place"],
        id: "21",
      ),
      Product(
        title: "Mechanical Keyboard",
        price: 89.99,
        image: "https://i.pinimg.com/564x/3a/e7/d4/3ae7d4adf2c66d7d3d4f8c9c4f2c78b7.jpg",
        category: "Electronics",
        colors: ["Black", "White", "RGB"],
        description: "Professional mechanical gaming keyboard with customizable RGB",
        brand: "GameTech",
        material: "Aluminum and ABS",
        features: ["Cherry MX switches", "Per-key RGB", "N-key rollover", "USB-C detachable"],
        careInstructions: ["Clean with compressed air", "Use keycap puller for cleaning"],
        id: "22",
      ),
      Product(
        title: "Gaming Headset",
        price: 69.99,
        image: "https://i.pinimg.com/564x/7c/85/c9/7c85c9b58647e2d5b1a9b2ca6c0c5992.jpg",
        category: "Electronics",
        colors: ["Black", "Red", "Blue"],
        description: "Professional gaming headset with 7.1 surround sound",
        brand: "AudioPro",
        material: "Premium Plastic and Memory Foam",
        features: ["7.1 Surround", "Noise cancelling mic", "RGB lighting", "Memory foam ear cups"],
        careInstructions: ["Clean with soft cloth", "Store in cool place", "Avoid moisture"],
        id: "23",
      ),
      Product(
        title: "USB-C Hub",
        price: 45.99,
        image: "https://i.pinimg.com/564x/8b/c9/2a/8bc92a9f3289be1834f4f2c564515b6b.jpg",
        category: "Electronics",
        colors: ["Silver", "Space Grey", "Black"],
        description: "10-in-1 USB-C hub with multiple ports and fast charging",
        brand: "TechConnect",
        material: "Aluminum Alloy",
        features: ["4K HDMI", "100W Power Delivery", "SD card reader", "Gigabit Ethernet"],
        careInstructions: ["Keep ports clean", "Avoid water exposure", "Store in case"],
        id: "24",
      ),
      Product(
        title: "Laptop Stand",
        price: 29.99,
        image: imgP3,
        category: "Electronics",
        colors: ["Silver", "Black", "Rose Gold"],
        description: "Ergonomic adjustable laptop stand",
        brand: "ErgoPro",
        material: "Aluminum Alloy",
        features: ["6 height levels", "Foldable design", "Heat dissipation", "Non-slip pads"],
        careInstructions: ["Clean with damp cloth", "Check rubber pads regularly", "Store flat"],
        id: "25",
      ),
      Product(
        title: "4K Monitor",
        price: 299.99,
        image: "https://i.pinimg.com/564x/7a/c5/28/7ac528c68b3b2db1f5f69c64d670c2df.jpg",
        category: "Electronics",
        colors: ["Black"],
        description: "Professional 4K monitor with HDR support",
        brand: "ViewTech",
        material: "Aluminum and Plastic",
        features: ["4K resolution", "HDR10", "USB-C hub", "Adjustable stand"],
        careInstructions: ["Clean with microfiber cloth", "Avoid liquid cleaners"],
        id: "26",
      ),
      Product(
        title: "Wireless Keyboard",
        price: 79.99,
        image: imgP3,
        category: "Electronics",
        colors: ["White", "Black", "Grey"],
        description: "Slim wireless keyboard with multi-device support",
        brand: "TechType",
        material: "Aluminum and ABS",
        features: ["Backlit keys", "3-month battery", "Multi-device pairing", "Low profile"],
        careInstructions: ["Clean between keys", "Replace batteries promptly", "Store in dry place"],
        id: "27",
      ),
      Product(
        title: "External SSD",
        price: 129.99,
        image: imgP3,
        category: "Electronics",
        colors: ["Black", "Blue"],
        description: "High-speed portable SSD with encryption",
        brand: "DataPro",
        material: "Aluminum",
        features: ["1TB storage", "USB 3.2", "Password protection", "Shock resistant"],
        careInstructions: ["Keep away from magnets", "Eject properly", "Store in case"],
        id: "28",
      ),
      Product(
        title: "Webcam HD",
        price: 59.99,
        image: imgP3,
        category: "Electronics",
        colors: ["Black"],
        description: "1080p HD webcam with built-in microphone",
        brand: "ViewCam",
        material: "ABS Plastic and Glass",
        features: ["1080p resolution", "Dual microphones", "Auto focus", "Low-light correction"],
        careInstructions: ["Clean lens regularly", "Keep covered when not in use", "Avoid touching lens"],
        id: "29",
      ),
      Product(
        title: "Gaming Mouse Pad",
        price: 19.99,
        image: imgP3,
        category: "Electronics",
        colors: ["Black", "RGB"],
        description: "Extended gaming mouse pad with RGB lighting",
        brand: "GamePro",
        material: "Micro-weave Fabric and Natural Rubber",
        features: ["RGB edges", "Non-slip base", "Water-resistant", "XXL size"],
        careInstructions: ["Hand wash only", "Air dry flat", "Avoid direct sunlight"],
        id: "30",
      ),
    ],
    'Cars': [
      Product(
        title: "Car Phone Mount",
        price: 19.99,
        image: imgP4,
        category: "Cars",
        colors: ["Black", "Grey", "Silver"],
        description: "Universal car phone mount with strong suction",
        brand: "DriveSecure",
        material: "ABS and Silicone",
        features: ["360° rotation", "One-touch release", "Dashboard compatible", "Adjustable arm"],
        careInstructions: ["Clean suction cup regularly", "Avoid direct sunlight", "Check stability daily"],
        id: "31",
      ),
      Product(
        title: "Car Air Freshener",
        price: 9.99,
        image: "https://i.pinimg.com/564x/d2/f1/66/d2f166f7edf8596f1c60f2c5ea4ac410.jpg",
        category: "Cars",
        colors: ["Ocean", "Lavender", "Pine"],
        description: "Long-lasting car air freshener with natural scents",
        brand: "FreshDrive",
        material: "Natural Essential Oils",
        features: ["3-month lasting", "Adjustable intensity", "Natural ingredients", "Clip design"],
        careInstructions: ["Replace every 3 months", "Keep away from direct sunlight", "Adjust as needed"],
        id: "32",
      ),
      Product(
        title: "Tire Pressure Gauge",
        price: 15.99,
        image: "https://i.pinimg.com/564x/e5/bd/6e/e5bd6e2e8887646f14b16df4f3e7f9d5.jpg",
        category: "Cars",
        colors: ["Black", "Blue", "Red"],
        description: "Digital tire pressure gauge with LCD display",
        brand: "AutoTech",
        material: "Stainless Steel and ABS",
        features: ["Backlit display", "Multiple units", "Auto-off", "Non-slip grip"],
        careInstructions: ["Keep battery fresh", "Store in dry place", "Clean after use"],
        id: "33",
      ),
      Product(
        title: "Car Vacuum Cleaner",
        price: 39.99,
        image: imgP4,
        category: "Cars",
        colors: ["Black", "Grey", "White"],
        description: "Powerful handheld car vacuum with LED light",
        brand: "AutoClean",
        material: "ABS Plastic",
        features: ["12V power", "HEPA filter", "LED light", "Multiple attachments"],
        careInstructions: ["Empty dust bin after use", "Wash filter monthly", "Store in car"],
        id: "34",
      ),
      Product(
        title: "Car Seat Cover",
        price: 49.99,
        image: imgP4,
        category: "Cars",
        colors: ["Black", "Grey", "Beige"],
        description: "Universal fit car seat covers with premium comfort",
        brand: "ComfortDrive",
        material: "Premium Leather and Mesh",
        features: ["Universal fit", "Easy installation", "Breathable material", "Waterproof"],
        careInstructions: ["Wipe clean", "Vacuum regularly", "Spot clean stains"],
        id: "35",
      ),
      Product(
        title: "Car Dash Cam",
        price: 89.99,
        image: "https://i.pinimg.com/564x/b5/c6/ca/b5c6caa3f5c2b18573e7c8e5fcf595c2.jpg",
        category: "Cars",
        colors: ["Black"],
        description: "1080p dash cam with night vision",
        brand: "DriveSafe",
        material: "ABS and Glass",
        features: ["Night vision", "Loop recording", "G-sensor", "Wide angle lens"],
        careInstructions: ["Clean lens monthly", "Check SD card regularly", "Update firmware"],
        id: "35",
      ),
      Product(
        title: "Car Jump Starter",
        price: 79.99,
        image: imgP4,
        category: "Cars",
        colors: ["Red", "Black"],
        description: "Portable jump starter with built-in flashlight",
        brand: "PowerStart",
        material: "ABS and Metal",
        features: ["12000mAh capacity", "LED flashlight", "USB charging", "Safety protection"],
        careInstructions: ["Charge monthly", "Store in cool place", "Keep away from water"],
        id: "36",
      ),
      Product(
        title: "Car Floor Mats",
        price: 49.99,
        image: imgP4,
        category: "Cars",
        colors: ["Black", "Beige", "Grey"],
        description: "All-weather floor mats set of 4",
        brand: "AutoShield",
        material: "Heavy-duty Rubber",
        features: ["Non-slip backing", "Waterproof", "Custom fit", "Easy to clean"],
        careInstructions: ["Wash with soap", "Air dry", "Vacuum regularly"],
        id: "37",
      ),
      Product(
        title: "Car Bluetooth Adapter",
        price: 25.99,
        image: imgP4,
        category: "Cars",
        brand: "TechConnect",
        material: "ABS Plastic",
        colors: ["Black"],
        description: "Bluetooth adapter for car audio system",
        id: "38",
        features: ["Hands-free calling", "Music streaming", "Voice control"],
        careInstructions: ["Keep clean", "Protect from heat", "Check connections"],
      ),
      Product(
        title: "Car Trunk Organizer", 
        price: 34.99,
        image: imgP4,
        category: "Cars",
        brand: "CargoMaster",
        material: "Oxford Fabric",
        colors: ["Black", "Grey"],
        description: "Collapsible trunk organizer with multiple compartments",
        id: "39",
      ),
    ],
    'Kids Clothing': [
      Product(
        title: "Educational Building Blocks",
        price: 34.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Multicolor"],
        description: "Interactive building blocks for early learning",
        brand: "KidsLearn",
        material: "Non-toxic ABS Plastic",
        features: ["Age 3+", "50 pieces", "Storage box", "Learning guide"],
        careInstructions: ["Hand wash", "Air dry", "Store in container"],
        id: "40",
      ),
      Product(
        title: "Building Block Robot Kit",
        price: 49.99,
        image: imgP5,
        category: "Kids Clothing",
        brand: "RoboTech",
        material: "ABS Plastic",
        colors: ["Blue", "Red", "Yellow"],
        description: "Interactive robot building kit with remote control",
        id: "41",
      ),
      Product(
        title: "Art Supply Set",
        price: 29.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Multicolor"],
        description: "Complete art supply set for creative kids",
        brand: "ArtKraft",
        material: "Mixed Materials",
        features: ["100+ pieces", "Storage case", "Non-toxic", "Age 6+"],
        careInstructions: ["Keep caps closed", "Clean after use", "Store upright"],
        id: "42",
      ),
      Product(
        title: "Plush Animal Collection",
        price: 19.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Multicolor"],
        description: "Set of soft plush animals for kids",
        brand: "CuddlePals",
        material: "Premium Plush",
        features: ["Machine washable", "Child safe", "Set of 5", "Hypoallergenic"],
        careInstructions: ["Machine wash gentle", "Air dry", "Spot clean when possible"],
        id: "43",
      ),
      Product(
        title: "Science Experiment Kit",
        price: 39.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Multicolor"],
        description: "Educational science kit with 40+ experiments",
        brand: "SmartLab",
        material: "Lab-grade Materials",
        features: ["40+ experiments", "Instruction manual", "Safety equipment", "Storage box"],
        careInstructions: ["Adult supervision", "Clean after use", "Store safely"],
        id: "44",
      ),
      Product(
        title: "Remote Control Car",
        price: 44.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Red", "Blue", "Green"],
        description: "High-speed remote control car with stunts",
        brand: "SpeedKing",
        material: "Durable Plastic",
        features: ["4WD", "Rechargeable", "Stunt mode", "LED lights"],
        careInstructions: ["Charge fully", "Clean after use", "Store in dry place"],
        id: "45",
      ),
      Product(
        title: "Board Game Set",
        price: 29.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Multicolor"],
        description: "Classic board games collection",
        brand: "GameMaster",
        material: "Cardboard and Plastic",
        features: ["6 games included", "Family friendly", "Storage box", "Ages 6+"],
        careInstructions: ["Keep all pieces together", "Store flat", "Handle with care"],
        id: "46",
      ),
      Product(
        title: "Musical Keyboard",
        price: 39.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Black", "White"],
        description: "Educational musical keyboard for beginners",
        brand: "MusicMaker",
        material: "ABS Plastic",
        features: ["32 keys", "Demo songs", "Recording function", "Battery operated"],
        careInstructions: ["Clean with dry cloth", "Remove batteries", "Store in case"],
        id: "47",
      ),
      Product(
        title: "Puzzle Set",
        price: 19.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Multicolor"],
        description: "Set of 4 educational puzzles",
        brand: "BrainTeaser",
        material: "High-quality Cardboard",
        features: ["Age-appropriate", "Different difficulty levels", "Educational themes", "Storage box"],
        careInstructions: ["Keep pieces together", "Store flat", "Handle with care"],
        id: "48",
      ),
      Product(
        title: "Drawing Tablet",
        price: 24.99,
        image: imgP5,
        category: "Kids Clothing",
        colors: ["Blue", "Pink", "Green"],
        description: "Digital drawing tablet for kids",
        brand: "CreativeKids",
        material: "LCD Screen with ABS Frame",
        features: ["8.5-inch screen", "Battery powered", "One-click erase", "Stylus included"],
        careInstructions: ["Clean screen gently", "Replace battery when needed", "Store in case"],
        id: "49",
      ),
    ],
    'Sports': [
      Product(
        title: "Basketball",
        price: 19.99,
        image: imgP6,
        category: "Sports",
        colors: ["Orange", "Brown"],
        description: "Official size basketball with superior grip",
        brand: "SportsPro",
        material: "Composite Leather",
        features: ["Official size", "Deep channel design", "Indoor/Outdoor use"],
        careInstructions: ["Keep inflated", "Clean with damp cloth", "Store indoors"],
        id: "50",
      ),
      Product(
        title: "Tennis Racket",
        price: 129.99,
        image: imgP6,
        category: "Sports",
        colors: ["Blue", "Black", "White"],
        description: "Professional tennis racket with case",
        brand: "ProSport",
        material: "Graphite Composite",
        features: ["Oversized head", "Shock absorption", "Includes cover", "Pre-strung"],
        careInstructions: ["Store in case", "Avoid extreme temperatures", "Replace grip regularly"],
        id: "51",
      ),
      Product(
        title: "Football",
        price: 29.99,
        image: imgP6,
        category: "Sports",
        colors: ["Brown"],
        description: "Official size football with enhanced grip",
        brand: "GameDay",
        material: "Premium Leather",
        features: ["Official size", "All-weather", "Enhanced grip", "Air-lock bladder"],
        careInstructions: ["Keep properly inflated", "Clean after use", "Store indoors"],
        id: "52",
      ),
      Product(
        title: "Treadmill",
        price: 499.99,
        image: imgP6,
        category: "Sports",
        colors: ["Black", "Silver"],
        description: "Foldable treadmill with LCD display",
        brand: "FitTech",
        material: "Steel Frame with ABS",
        features: ["12 programs", "Heart rate monitor", "Foldable design", "LCD display"],
        careInstructions: ["Lubricate belt monthly", "Clean after use", "Keep plugs dry"],
        id: "53",
      ),
      Product(
        title: "Yoga Mat",
        price: 19.99,
        image: imgP6,
        category: "Sports",
        colors: ["Black", "Grey", "Green"],
        description: "Non-slip yoga mat for home workouts",
        brand: "ZenFit",
        material: "TPE Eco-friendly Foam",
        features: ["6mm thickness", "Non-slip surface", "Alignment lines", "Carrying strap"],
        careInstructions: ["Wipe clean after use", "Air dry", "Roll for storage"],
        id: "54",
      ),
      Product(
        title: "Bicycle",
        price: 299.99,
        image: imgP6,
        category: "Sports",
        colors: ["Red", "Black", "White"],
        description: "High-quality bicycle for all terrains",
        brand: "SpeedCycle",
        material: "Aluminum Frame",
        features: ["21-speed gears", "Disc brakes", "Adjustable seat", "Front suspension"],
        careInstructions: ["Regular maintenance", "Keep chain lubricated", "Store indoors"],
        id: "55",
      ),
      Product(
        title: "Swimming Goggles",
        price: 14.99,
        image: imgP6,
        category: "Sports",
        colors: ["Clear"],
        description: "Clear swimming goggles for water activities",
        brand: "AquaPro",
        material: "Silicone and Polycarbonate",
        features: ["Anti-fog", "UV protection", "Adjustable strap", "Watertight seal"],
        careInstructions: ["Rinse after use", "Store in case", "Replace if damaged"],
        id: "56",
      ),
      Product(
        title: "Running Shoes",
        price: 89.99,
        image: imgP6,
        category: "Sports",
        colors: ["Black", "White", "Grey"],
        description: "High-performance running shoes",
        brand: "SpeedRunner",
        material: "Mesh and Synthetic",
        features: ["Cushioned sole", "Breathable mesh", "Arch support", "Reflective details"],
        careInstructions: ["Air dry only", "Clean with brush", "Rotate pairs"],
        id: "57",
      ),
      Product(
        title: "Gym Bag",
        price: 29.99,
        image: imgP6,
        category: "Sports",
        colors: ["Black", "Navy", "Grey"],
        description: "Spacious gym bag with compartments",
        brand: "FitGear",
        material: "Water-resistant Polyester",
        features: ["Shoe compartment", "Wet pocket", "Multiple pockets", "Adjustable strap"],
        careInstructions: ["Wipe clean", "Air dry", "Check zippers regularly"],
        id: "58",
      ),
      Product(
        title: "Weight Bench",
        price: 199.99,
        image: imgP6,
        category: "Sports",
        colors: ["Black", "Grey", "Red"],
        description: "Adjustable weight bench for home workouts",
        brand: "PowerFit",
        material: "Steel Frame with Padded Vinyl",
        features: ["Multiple positions", "Foldable design", "800lb capacity", "Non-slip feet"],
        careInstructions: ["Wipe clean after use", "Check bolts regularly", "Store indoors"],
        id: "59",
      ),
    ],
    'Home Garden': [
      Product(
        title: "Garden Tool Set",
        price: 49.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Green", "Black"],
        description: "Complete garden tool set with carrying case",
        brand: "GardenPro",
        material: "Stainless Steel and Ergonomic Handles",
        features: ["10 pieces", "Carrying case", "Ergonomic grips", "Rust resistant"],
        careInstructions: ["Clean after use", "Store in dry place", "Oil metal parts"],
        id: "60",
      ),
      Product(
        title: "Plant Pots Set",
        price: 29.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Terracotta", "White", "Grey"],
        description: "Set of 5 decorative plant pots with drainage",
        brand: "GreenThumb",
        material: "Ceramic with Drainage",
        features: ["Drainage holes", "Saucers included", "Various sizes", "Indoor/Outdoor"],
        careInstructions: ["Clean before use", "Empty excess water", "Handle with care"],
        id: "61",
      ),
      Product(
        title: "Lawn Mower",
        price: 299.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Green", "Black"],
        description: "Electric lawn mower with grass collection bag",
        brand: "YardMaster",
        material: "Steel and ABS Plastic",
        features: ["Adjustable height", "40L collection bag", "Folding handle", "Safety switch"],
        careInstructions: ["Clean after use", "Store in dry place", "Sharpen blades yearly"],
        id: "62",
      ),
      Product(
        title: "Garden Hose",
        price: 34.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Green", "Blue"],
        description: "50ft expandable garden hose with spray nozzle",
        brand: "WaterPro",
        material: "Triple Layer Latex",
        features: ["Expandable design", "8-pattern nozzle", "Brass fittings", "Kink-free"],
        careInstructions: ["Drain after use", "Store in shade", "Avoid freezing"],
        id: "63",
      ),
      Product(
        title: "Solar Garden Lights",
        price: 39.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Silver", "Bronze", "Black"],
        description: "Set of 8 solar-powered pathway lights",
        brand: "SolarGlow",
        material: "Stainless Steel and Plastic",
        features: ["Solar powered", "Auto on/off", "Weatherproof", "Easy installation"],
        careInstructions: ["Clean solar panels", "Check batteries yearly", "Remove snow"],
        id: "64",
      ),
      Product(
        title: "Bird Feeder",
        price: 24.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Brown", "Green"],
        description: "Decorative bird feeder with rain guard",
        brand: "WildLife",
        material: "Weather-resistant Plastic",
        features: ["Rain protection", "Easy refill", "Pest proof", "4lb capacity"],
        careInstructions: ["Clean monthly", "Check drainage", "Refill regularly"],
        id: "65",
      ),
      Product(
        title: "Pruning Shears",
        price: 19.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Red", "Black"],
        description: "Professional grade pruning shears",
        brand: "GardenPro",
        material: "High-carbon Steel",
        features: ["Ergonomic grip", "Safety lock", "Replaceable blade", "Spring loaded"],
        careInstructions: ["Clean after use", "Oil joints", "Sharpen regularly"],
        id: "66",
      ),
      Product(
        title: "Watering Can",
        price: 15.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Green", "Blue", "Pink"],
        description: "2-gallon decorative watering can",
        brand: "GardenBasics",
        material: "Recycled Plastic",
        features: ["Removable rose", "Ergonomic handle", "Wide opening", "Balance design"],
        careInstructions: ["Empty after use", "Store upright", "Clean regularly"],
        id: "67",
      ),
      Product(
        title: "Compost Bin",
        price: 59.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["Black", "Green"],
        description: "Outdoor compost bin with lid",
        brand: "EcoGarden",
        material: "UV-resistant Plastic",
        features: ["Ventilation holes", "Secure lid", "80-gallon capacity", "Bottom door"],
        careInstructions: ["Turn compost weekly", "Monitor moisture", "Clean yearly"],
        id: "68",
      ),
      Product(
        title: "Garden Bench",
        price: 129.99,
        image: imgP7,
        category: "Home Garden",
        colors: ["White", "Brown", "Green"],
        description: "Weather-resistant garden bench",
        brand: "OutdoorLiving",
        material: "Teak Wood",
        features: ["Weather resistant", "Ergonomic design", "Easy assembly", "3-seater"],
        careInstructions: ["Oil annually", "Cover in winter", "Tighten bolts regularly"],
        id: "69",
      ),
    ],
    'Beauty': [
      Product(
        title: "Face Cream",
        price: 29.99,
        image: imgP8,
        category: "Beauty",
        colors: ["White"],
        description: "Hydrating face cream with natural ingredients",
        brand: "PureGlow",
        material: "Natural and Organic Ingredients",
        features: ["24h hydration", "Non-comedogenic", "Fragrance-free"],
        careInstructions: ["Store in cool place", "Use within 12 months", "Apply twice daily"],
        id: "70",
      ),
      Product(
        title: "Lipstick Set",
        price: 39.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Red", "Pink", "Nude"],
        description: "Set of 5 long-lasting lipsticks",
        brand: "GlamBeauty",
        material: "Vegan Wax and Oils",
        features: ["Long-lasting", "Moisturizing", "Cruelty-free", "Matte finish"],
        careInstructions: ["Store upright", "Keep away from heat", "Check expiration date"],
        id: "71",
      ),
      Product(
        title: "Hair Dryer",
        price: 79.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Black", "Pink", "White"],
        description: "Professional ionic hair dryer",
        brand: "StylePro",
        material: "Professional Grade Plastic",
        features: ["Ionic technology", "Multiple heat settings", "Cool shot button", "Concentrator nozzle"],
        careInstructions: ["Clean filter monthly", "Store unplugged", "Check cord regularly"],
        id: "72",
      ),
      Product(
        title: "Makeup Brushes",
        price: 49.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Rose Gold", "Black"],
        description: "12-piece makeup brush set with case",
        brand: "BeautyPro",
        material: "Synthetic Bristles and Bamboo",
        features: ["12 brushes", "Travel case", "Cruelty-free", "Professional grade"],
        careInstructions: ["Clean monthly", "Air dry upright", "Store in case"],
        id: "73",
      ),
      Product(
        title: "Perfume",
        price: 89.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Gold", "Silver"],
        description: "Luxury perfume with floral notes",
        brand: "LuxScent",
        material: "Natural and Synthetic Fragrances",
        features: ["50ml bottle", "Long-lasting", "Signature scent", "Gift box"],
        careInstructions: ["Store in cool place", "Keep away from sunlight", "Replace cap tightly"],
        id: "74",
      ),
      Product(
        title: "Face Mask Set",
        price: 24.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Multi"],
        description: "Set of 10 sheet masks",
        brand: "SkinCare",
        material: "Natural Fiber Sheet",
        features: ["10 masks", "Various treatments", "Hydrating", "All skin types"],
        careInstructions: ["Check expiration", "Store sealed", "Use immediately once opened"],
        id: "75",
      ),
      Product(
        title: "Nail Polish Set",
        price: 34.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Multi"],
        description: "Set of 12 nail polishes",
        brand: "NailArt",
        material: "Non-toxic Formula",
        features: ["12 colors", "Quick dry", "Long-lasting", "Non-chip"],
        careInstructions: ["Shake well", "Keep tightly closed", "Store upright"],
        id: "76",
      ),
      Product(
        title: "Hair Straightener",
        price: 59.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Black", "Pink"],
        description: "Ceramic hair straightener with LCD display",
        brand: "HairPro",
        material: "Ceramic Plates",
        features: ["LCD display", "Adjustable temp", "Auto shutoff", "Dual voltage"],
        careInstructions: ["Clean when cool", "Store unplugged", "Check cord regularly"],
        id: "77",
      ),
      Product(
        title: "Eye Shadow Palette",
        price: 44.99,
        image: imgP8,
        category: "Beauty",
        colors: ["Multi"],
        description: "18-color eyeshadow palette",
        brand: "MakeupArt",
        material: "Pressed Powder",
        features: ["18 shades", "Mirror included", "Brush included", "Mix of finishes"],
        careInstructions: ["Close tightly", "Keep clean brush", "Store away from heat"],
        id: "78",
      ),
      Product(
        title: "Beauty Mirror",
        price: 69.99,
        image: imgP8,
        category: "Beauty",
        colors: ["White", "Rose Gold"],
        description: "LED lighted makeup mirror",
        brand: "GlamView",
        material: "Glass and ABS Plastic",
        features: ["LED lighting", "3x magnification", "Adjustable angle", "USB charging"],
        careInstructions: ["Clean with cloth", "Avoid water contact", "Store flat"],
        id: "79",
      ),
    ],
    'Furniture': [
      Product(
        title: "Sofa Set",
        price: 999.99,
        image: imgP9,
        category: "Furniture",
        colors: ["Grey", "Beige", "Blue"],
        description: "Modern 3-piece sofa set with premium upholstery",
        brand: "HomeStyle",
        material: "Premium Fabric and Solid Wood",
        features: ["3 pieces", "High-density foam", "Removable cushions", "Sturdy frame"],
        careInstructions: ["Vacuum regularly", "Spot clean stains", "Rotate cushions monthly"],
        id: "80",
      ),
      Product(
        title: "Dining Table",
        price: 599.99,
        image: imgP9,
        category: "Furniture",
        colors: ["Brown", "White", "Black"],
        description: "6-seater wooden dining table",
        brand: "DineStyle",
        material: "Solid Wood",
        features: ["Seats 6", "Sturdy construction", "Scratch resistant", "Assembly required"],
        careInstructions: ["Clean with wood cleaner", "Use coasters", "Avoid direct sunlight"],
        id: "81",
      ),
      Product(
        title: "Bed Frame",
        price: 499.99,
        image: imgP9,
        category: "Furniture",
        colors: ["Grey", "Brown", "White"],
        description: "Queen size bed frame with headboard",
        brand: "SleepWell",
        material: "Solid Wood and Metal",
        features: ["Queen size", "Built-in slats", "Upholstered headboard", "Easy assembly"],
        careInstructions: ["Tighten bolts regularly", "Vacuum headboard", "Check slats monthly"],
        id: "82",
      ),
      Product(
        title: "Wardrobe",
        price: 399.99,
        image: imgP9,
        category: "Furniture",
        colors: ["White", "Brown", "Black"],
        description: "3-door wardrobe with mirror",
        brand: "StoragePro",
        material: "Engineered Wood",
        features: ["Full mirror", "Hanging rail", "Shelves", "Drawer unit"],
        careInstructions: ["Clean mirror weekly", "Check hinges", "Keep doors aligned"],
        id: "83",
      ),
      Product(
        title: "Coffee Table",
        price: 199.99,
        image: imgP9,
        category: "Furniture",
        colors: ["Walnut", "White", "Black"],
        description: "Modern coffee table with storage",
        brand: "ModernLiving",
        material: "MDF with Wood Veneer",
        features: ["Hidden storage", "Lift top", "Anti-scratch surface", "Modern design"],
        careInstructions: ["Use coasters", "Dust regularly", "Clean spills immediately"],
        id: "84",
      ),
      Product(
        title: "Bookshelf",
        price: 149.99,
        image: imgP9,
        category: "Furniture",
        colors: ["White", "Brown", "Black"],
        description: "5-tier bookshelf with adjustable shelves",
        brand: "OrganizeIt",
        material: "Steel and Particleboard",
        features: ["5 tiers", "Adjustable shelves", "Wall anchor", "Weight capacity 30kg/shelf"],
        careInstructions: ["Check stability monthly", "Clean with damp cloth", "Adjust shelf level as needed"],
        id: "85",
      ),
      Product(
        title: "TV Stand",
        price: 249.99,
        image: imgP9,
        category: "Furniture",
        colors: ["Black", "White", "Brown"],
        description: "TV stand with cable management",
        brand: "MediaPro",
        material: "MDF and Tempered Glass",
        features: ["Cable management", "Glass shelves", "Up to 65\" TV", "Storage cabinets"],
        careInstructions: ["Clean glass weekly", "Manage cables", "Check door alignment"],
        id: "86",
      ),
      Product(
        title: "Office Desk",
        price: 299.99,
        image: imgP9,
        category: "Furniture",
        colors: ["White", "Brown", "Black"],
        description: "Computer desk with drawers",
        brand: "WorkSpace",
        material: "Steel Frame and Wood Top",
        features: ["File drawer", "Cable grommets", "Keyboard tray", "Adjustable feet"],
        careInstructions: ["Clean surface daily", "Oil drawer slides", "Check stability"],
        id: "87",
      ),
      Product(
        title: "Accent Chair",
        price: 199.99,
        image: imgP9,
        category: "Furniture",
        colors: ["Grey", "Blue", "Yellow"],
        description: "Modern accent chair with ottoman",
        brand: "ComfortPlus",
        material: "Velvet and Solid Wood",
        features: ["Matching ottoman", "High backrest", "Foam padding", "Non-slip feet"],
        careInstructions: ["Vacuum weekly", "Rotate cushion", "Spot clean only"],
        id: "88",
      ),
      Product(
        title: "Side Table",
        price: 89.99,
        image: imgP9,
        category: "Furniture",
        colors: ["White", "Black", "Natural"],
        description: "Wooden side table with shelf",
        brand: "SimpleLiving",
        material: "Bamboo Wood",
        features: ["Lower shelf", "Compact size", "Easy assembly", "Natural finish"],
        careInstructions: ["Dust regularly", "Use coasters", "Avoid moisture"],
        id: "89",
      ),
    ],
  };

  void increaseQuantity() {
    if (quantity.value < 99) {
      quantity.value++;
    }
  }

  void decreaseQuantity() {
    if (quantity.value > 1) {
      quantity.value--;
    }
  }

  void setColorIndex(int index) {
    colorIndex.value = index;
  }

  void setCurrentCategory(String category) {
    currentCategory.value = category;
    // Create a new observable list for the current category products
    final products = categoryProducts[category] ?? [];
    relatedProducts.assignAll(products);
    update();
  }

  RxList<Product> get currentCategoryProducts => relatedProducts;

  void setCurrentProduct({
    required String title,
    required double price,
  }) {
    currentProductTitle.value = title;
    currentProductPrice.value = price;
    
    // Find and set the actual product object
    for (var category in categoryProducts.keys) {
      for (var product in categoryProducts[category]!) {
        if (product.title == title) {
          currentProduct.value = product;
          break;
        }
      }
    }
    
    // Reset quantity and color when viewing new product
    quantity.value = 1;
    colorIndex.value = 0;
    sizeIndex.value = 0;
  }

  void toggleFavorite(int index) {
    if (favorites.contains(index)) {
      favorites.remove(index);
    } else {
      favorites.add(index);
    }
  }

  bool isFavorite(int index) {
    return favorites.contains(index);
  }

  void setRelatedProducts(List<Product> products) {
    relatedProducts.value = products;
  }

  void setSizeIndex(int index) {
    sizeIndex.value = index;
  }

  void addToCart(Product product) {
    cartItems.add(product);
    updateCartTotal();
  }

  void buyNow(Product product) {
    addToCart(product);
    // Navigate to checkout or cart page
    Get.toNamed('/cart');
  }

  void updateCartTotal() {
    cartTotal.value = 0;
    for (var item in cartItems) {
      cartTotal.value += item.price;
    }
  }
}
